// The code is generated by github.com/ngicks/musicbox/composeloader/cmd/gentypes
// DO NOT EDIT.
package example

import (
	"io/fs"

	"github.com/spf13/afero"
)

type DirSet struct {
	Foo string
	Bar string
	Baz string
}

type DirHandle struct {
	Foo afero.Fs
	Bar afero.Fs
	Baz afero.Fs
}

type DirContents struct {
	Foo fs.FS
	Bar fs.FS
	Baz fs.FS
}
