package main

import (
	"bytes"
	"flag"
	"html/template"
	"io"
	"os"
	"strings"
)

var (
	pkg    = flag.String("pkg", "", "package name for generated go code.")
	prefix = flag.String("prefix", "Dir", "prefix for generated types. It'll generate <prefix>Set, <prefix>Handle, <prefix>Contents.")
	fields = flag.String("fields", "", "comma separated fields names for generated types.")
	out    = flag.String("o", "-", "path to output file. `-` means stdout.")
)

type tempInput struct {
	PkgName string
	Prefix  string
	Fields  []string
}

var genTemp = template.Must(template.New("foo").Parse(`// The code is generated by github.com/ngicks/musicbox/composeloader/cmd/gentypes
// DO NOT EDIT.
package {{.PkgName}}

import (
	"io/fs"

	"github.com/spf13/afero"
)

type {{.Prefix}}Set struct {
{{range $index, $element := .Fields}}	{{$element}} string
{{end -}}
}

type {{.Prefix}}Handle struct {
{{range $index, $element := .Fields}}	{{$element}} afero.Fs
{{end -}}
}

type {{.Prefix}}Contents struct {
{{range $index, $element := .Fields}}	{{$element}} fs.FS
{{end -}}
}
`))

func main() {
	flag.Parse()

	if *pkg == "" {
		panic("pkg is not specified")
	}
	if *fields == "" {
		panic("fields is not specified")
	}

	fieldsSlice := strings.Split(*fields, ",")

	buf := new(bytes.Buffer)

	err := genTemp.Execute(buf, tempInput{
		PkgName: *pkg,
		Prefix:  *prefix,
		Fields:  fieldsSlice,
	})
	if err != nil {
		panic(err)
	}

	var outFile *os.File
	if *out == "-" || *out == "--" {
		outFile = os.Stdout
	} else {
		f, err := os.Create(*out)
		if err != nil {
			panic(err)
		}
		defer func() { _ = f.Close() }()
		outFile = f
	}

	_, err = io.Copy(outFile, buf)
	if err != nil {
		panic(err)
	}
}
