// The code is generated by github.com/ngicks/musicbox/composeloader/cmd/gentypes
// DO NOT EDIT.
package example

import (
	"io/fs"

	"github.com/ngicks/musicbox/storage"
	"github.com/spf13/afero"
)

func PreparePath(
	base afero.Fs,
	pathSet PathSet,
	initialContents PathContents,
) (PathHandle, error) {
	return storage.PrepareHandle[PathSet, PathHandle](base, pathSet, initialContents)
}

type PathSet struct {
	Foo string
	Bar string
	Baz string
}

type PathHandle struct {
	Foo afero.Fs
	Bar afero.Fs
	Baz afero.Fs
}

type PathContents struct {
	Foo fs.FS
	Bar fs.FS
	Baz fs.FS
}
