// The code is generated by github.com/ngicks/musicbox/composeloader/cmd/gentypes
// DO NOT EDIT.
package example

import (
	"io/fs"

	"github.com/ngicks/musicbox/storage"
	"github.com/spf13/afero"
)

func PrepareDir(
	base afero.Fs,
	pathSet DirSet,
	initialContents DirContents,
) (pathHandle, error) {
	return storage.PrepareHandle[DirSet, pathHandle](base, pathSet, initialContents)
}

type DirSet struct {
	Foo string
	Bar string
	Baz string
}

type pathHandle struct {
	Foo afero.Fs
	Bar afero.Fs
	Baz afero.Fs
}

type DirContents struct {
	Foo fs.FS
	Bar fs.FS
	Baz fs.FS
}
